# Generated by Django 2.2.1 on 2019-05-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0003_auto_20190509_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='false', upload_to='bender/static/img/products'),
        ),
    ]
