# Generated by Django 2.2.1 on 2019-05-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0004_auto_20190509_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='false', upload_to='bender/static/img/products'),
        ),
    ]
